### ISSUE TITLE
Tutorial isn't helping at all

### ISSUE THREAD

**Issue by Blackening999** [philipheinser/ember-lightning#15]
When I followed all instructions in README - error happened

root@production:~/ember-lightning# docker run --name 'my-project-name' ember-lightning:latest
Redis client error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
Redis client error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
Redis client error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
Redis client error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
Redis client error: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379

**Comment by philipheinser** [comment]
@Blackening999 you need a redisserver to run in your running environment

**Comment by Blackening999** [comment]
@philipheinser 
Yep, I understood that, but it isn't helpful at all. Should I have redis server started inside your container or outside? How should I link them? I have no idea how to get your container working. I haven't worked with Docker before.
Can you provide working example? Or at least sequence of actions I should execute to make container it working. Also Redis isn't a simple topic, to config deploys I might need custom redis.conf etc., so the biggest question is how to connect all of the stuff so it simply works.

**Comment by Blackening999** [comment]
I have used you library before ember-cli-deploy 0.5.0 (but just as a index.js + app.json, no docker), but then they've upgraded with breaking changes and no backward compatibility and no good examples on how to upgrade. The ember side of upgrade process is clear even for dummies, but proxy-server path is unclear at some point.
I saw that Docker might be a great option.
So I think if you can provde better docs you could save lots of time for the ones who wants to build this part of deployment schema

**Comment by philipheinser** [comment]
@inkblot Would you mind helping out?

**Comment by Blackening999** [comment]
@philipheinser 
@inkblot 
Also, have you got a chance to run '$ npm install' - it isn't working either

**Comment by inkblot** [comment]
@Blackening999 there are a couple of options for how and where you can run the redis server, but it should not be in the same container as the ember-lightning server. The ember-lightning container will use the value of its `REDIS_HOST` environment variable to connect to the redis server, and the default value is simply `redis` which is intended to take advantage of docker's linking feature, and intended to be overridden otherwise.

To use the ember-lightning docker container with redis also running in a docker container, you'll need to start the redis container and then start the ember-lightning container with a link to the redis container, like this:

```
$ docker run --name ember-redis redis
$ docker run --name my-project-name --env APP_NAME=my-project-name --link ember-redis:redis ember-lightning:latest
```

In this example, the `my-project-name` container will use the default value for `REDIS_HOST`, which is `redis`. The `--link ember-redis:redis` sets up the container so that inside the container the DNS name `redis` will resolve to the `ember-redis` container which is started in the first command. There are many more options that you could provide when running the `ember-redis` container to enable things like persistent storage or to use a different `redis.conf`. These are thoroughly documented at the Docker Hub page for the Redis docker image: https://hub.docker.com/_/redis/

To use the ember-lightning docker container with a redis server that is not running in a docker container, or running in a container on a different host machine, you will need the hostname of the redis server, and you will need to start the ember-lightning container differently. Using `redis.mysite.internal` as the redis server, run ember-lightning like this:

```
$ docker run --name my-project-name --env APP_NAME=my-project-name --env REDIS_HOST=redis.mysite.internal ember-lightning:latest
```

This overrides the default value of `REDIS_HOST` instead of linking another container to the `redis` name, and the ember-lightning server running inside the container will connect in this case to the name `redis.mysite.internal` instead of `redis`.

Regardless of which method you use to run redis, your `ember-deploy` configuration in your ember project needs to deploy to it.

**Comment by Blackening999** [comment]
@inkblot Wow! Thank you for comprehensive explanation! It's more clear now. I have a few more questions before I can be confident in what I'm doing :)

1. Should I configure nginx in reverse-proxy mode to the outer Redis host ? (I think it's better connect redis from outside of container). I have a DO instance for front-end hosting, so when user hit some address, I'll redirect him to index.html.

I have this config for non-docker (ember-deploy 0.4.0, old)
```bash
server {
    listen 80;
    server_name website.com www.website.com;
    return 301 https://www.website.com$request_uri;
}

server {
    listen 443 ssl;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_ciphers "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS";
    ssl_dhparam     /etc/nginx/ssl/dhparam.pem;
    ssl_certificate /etc/nginx/ssl/website.com.crt;
    ssl_certificate_key /etc/nginx/ssl/website.com.key;

    access_log  /var/log/nginx/website.com.access.log main;
    error_log   /var/log/nginx/website.com.error.log;

    server_name website.com www.website.com;

    location / {
        proxy_pass http://localhost:8787;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        #proxy_set_header X-Prerender-Token prerendertoken;
        proxy_cache_bypass $http_upgrade;
    }
}
```

2. How can I make logging work? In case something configured wrong, all I can see now is "502 Bad Request", would be nice to have some output from node.js about what's wrong there.

Thank you for your help, getting closer to complete solution!

**Comment by inkblot** [comment]
nginx should reverse proxy ember-lightning, not redis.

**Comment by Blackening999** [comment]
@inkblot 
I have a binding in redis.conf like:
```
bind xxx.xxx.xx.xx 127.0.0.1
``` 

I think it binds redis to external ip marked as xxx.xxx.xx.xx .
And I had this on my prev. config. Which is not the case for a new version as far as I understand.

```json
{
      "APP_PORT": {
      "description": "The port the app runs on",
      "value": 8787
    }
}
```

8787 port is reversed by nginx conf.
So this should work correct, right?

**Comment by inkblot** [comment]
I have no idea, I've never configured redis before.

**Comment by Blackening999** [comment]
@inkblot 
Now, I start thinking that I'm unique :D 
How you guys making ember-cli-deploy work for you?
I thought this is the only way ember-lightning works

**Comment by inkblot** [comment]
In production, my redis server is an AWS Elasticache instance on a private VPC subnet which ember-cli-deploy can reach through private networks. ember-lightning is running in a docker container that has access to the redis server locally through the private VPC subnet. Web traffic is reverse proxied through an ELB to nginx to ember-lightning.

I only have a production redis server. In development I'm using ember server instead of ember-lightning so there's no need for redis. Hypothetically, though, if I were running ember-lightning in development, I would just run it and redis in docker containers and configure ember-cli-deploy to connect to localhost:6379.
